from app.models import db, Image

def seed_images():
    image1= Image(carId=1, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image2= Image(carId=1, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image3= Image(carId=1, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image4= Image(carId=1, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image5= Image(carId=1, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image6= Image(carId=2, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image7= Image(carId=2, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image8= Image(carId=2, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image9= Image(carId=2, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image10= Image(carId=2, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image11= Image(carId=3, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image12= Image(carId=3, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image13= Image(carId=3, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image14= Image(carId=3, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image15= Image(carId=3, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image16= Image(carId=4, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image17= Image(carId=4, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image18= Image(carId=4, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image19= Image(carId=4, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image20= Image(carId=4, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image21= Image(carId=5, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image22= Image(carId=5, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image23= Image(carId=5, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image24= Image(carId=5, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image25= Image(carId=5, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image26= Image(carId=6, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image27= Image(carId=6, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image28= Image(carId=6, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image29= Image(carId=6, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image30= Image(carId=6, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image31= Image(carId=7, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image32= Image(carId=7, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image33= Image(carId=7, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image34= Image(carId=7, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image35= Image(carId=7, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image36= Image(carId=8, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image37= Image(carId=8, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image38= Image(carId=8, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image39= Image(carId=8, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image40= Image(carId=8, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image41= Image(carId=9, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image42= Image(carId=9, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image43= Image(carId=9, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image44= Image(carId=9, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image45= Image(carId=9, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image46= Image(carId=10, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image47= Image(carId=10, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image48= Image(carId=10, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image49= Image(carId=10, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')
    image50= Image(carId=10, url='https://www.vhv.rs/dpng/d/52-520651_default-car-image-png-transparent-png.png')

    db.session.add(image1)
    db.session.add(image2)
    db.session.add(image3)
    db.session.add(image4)
    db.session.add(image5)
    db.session.add(image6)
    db.session.add(image7)
    db.session.add(image8)
    db.session.add(image9)
    db.session.add(image10)
    db.session.add(image11)
    db.session.add(image12)
    db.session.add(image13)
    db.session.add(image14)
    db.session.add(image15)
    db.session.add(image16)
    db.session.add(image17)
    db.session.add(image18)
    db.session.add(image19)
    db.session.add(image20)
    db.session.add(image21)
    db.session.add(image22)
    db.session.add(image23)
    db.session.add(image24)
    db.session.add(image25)
    db.session.add(image26)
    db.session.add(image27)
    db.session.add(image28)
    db.session.add(image29)
    db.session.add(image30)
    db.session.add(image31)
    db.session.add(image32)
    db.session.add(image33)
    db.session.add(image34)
    db.session.add(image35)
    db.session.add(image36)
    db.session.add(image37)
    db.session.add(image38)
    db.session.add(image39)
    db.session.add(image40)
    db.session.add(image41)
    db.session.add(image42)
    db.session.add(image43)
    db.session.add(image44)
    db.session.add(image45)
    db.session.add(image46)
    db.session.add(image47)
    db.session.add(image48)
    db.session.add(image49)
    db.session.add(image50)

    db.session.commit()

def undo_images():
    db.session.execute('TRUNCATE images RESTART IDENTITY CASCADE;')
    db.session.commit()
